# PHP 异常处理

> 原文：<https://www.tutorialrepublic.com/php-tutorial/php-exception-handling.php>

在本教程中，你将学习如何在 PHP 中抛出和捕捉异常。

## 什么是例外

异常是指示某种异常事件或错误已经发生的信号。异常可能是由于各种原因引起的，例如，数据库连接或查询失败，您试图访问的文件不存在，等等。

PHP 提供了一个强大的异常处理机制，允许您以一种优雅的方式处理异常。与 PHP 传统的[错误处理](php-error-handling.php)系统相反，异常处理是用于处理错误的[面向对象](php-classes-and-objects.php)方法，它提供了更加可控和灵活的错误报告形式。异常模型最初是在 PHP 5 中引入的。

## 使用投掷和尝试...Catch 语句

在基于异常的方法中，程序代码被写在一个`try`块中，当一个异常事件在`try`块中的代码执行期间发生时，可以使用`throw`语句抛出一个异常。然后它被一个或多个`catch`模块捕获并解析。

下面的示例演示了异常处理的工作原理:

#### 例子

[Download](../examples/bin/download-source.php?topic=php&file=throw-catch-exceptions "Download Source Code")

```
<?php
function division($dividend, $divisor){
    // Throw exception if divisor is zero
    if($divisor == 0){
        throw new Exception('Division by zero.');
    } else{
        $quotient = $dividend / $divisor;
        echo "<p>$dividend / $divisor = $quotient</p>";
    }
}

try{
    division(10, 2);
    division(30, -4);
    division(15, 0);

    // If exception is thrown following line won't execute
    echo '<p>All divisions performed successfully.</p>';
} catch(Exception $e){
    // Handle the exception
    echo "<p>Caught exception: " . $e->getMessage() . "</p>";
}

// Continue execution
echo "<p>Hello World!</p>";
?>
```

您可能想知道这段代码是关于什么的。好吧，为了更好地理解，让我们一个接一个地浏览这段代码的每一部分。

## 代码解释

PHP 的异常处理系统基本上有四个部分:`try`、`throw`、`catch`和异常类。下面的列表描述了每个部分的确切工作原理。

*   上例中的`division()`函数检查除数是否等于零。如果是，PHP 的`throw`语句会抛出一个异常。否则，该函数使用给定的数字执行除法并显示结果。
*   稍后，在具有不同参数的`try`块中调用`division()`函数。如果在执行`try`块中的代码时产生异常，PHP 将在该点停止执行，并试图找到相应的`catch`块。如果找到了，就执行那个`catch`块中的代码，如果没有找到，就会产生一个致命错误。
*   `catch`块通常捕获在`try`块中抛出的异常，并创建一个包含异常信息的对象(`$e`)。可以使用异常的`getMessage()`方法检索来自该对象的错误消息。

PHP 的异常类还提供了`getCode()`、`getFile()`、`getLine()`和`getTraceAsString()`方法，可以用来生成详细的调试信息。

#### 例子

[Download](../examples/bin/download-source.php?topic=php&file=exception-class-methods "Download Source Code")

```
<?php
// Turn off default error reporting
error_reporting(0);

try{
    $file = "somefile.txt";

    // Attempt to open the file
    $handle = fopen($file, "r");
    if(!$handle){
        throw new Exception("Cannot open the file!", 5);
    }

    // Attempt to read the file contents
    $content = fread($handle, filesize($file));
    if(!$content){
        throw new Exception("Could not read file!", 10);
    }

    // Closing the file handle
    fclose($handle);

    // Display file contents
    echo $content;
} catch(Exception $e){
    echo "<h3>Caught Exception!</h3>";
    echo "<p>Error message: " . $e->getMessage() . "</p>";    
    echo "<p>File: " . $e->getFile() . "</p>";
    echo "<p>Line: " . $e->getLine() . "</p>";
    echo "<p>Error code: " . $e->getCode() . "</p>";
    echo "<p>Trace: " . $e->getTraceAsString() . "</p>";
}
?>
```

异常的构造函数可以选择接受一条异常消息和一个异常代码。虽然异常消息通常用于显示出错原因的一般信息，但异常代码可用于对错误进行分类。稍后可以通过 exception 的`getCode()`方法检索提供的异常代码。

 ***提示:** Exception 应仅用于表示异常情况；它们不应用于控制正常的应用流，例如，在特定点跳转到脚本中的另一个位置。这样做会对应用的性能产生负面影响。*  ** * *

## 定义自定义例外

您甚至可以定义自己的自定义异常处理程序，以不同的方式处理不同类型的异常。它允许您为每个异常类型使用单独的`catch`块。

您可以通过扩展 exception 类来定义自定义异常，因为 Exception 是所有异常的基类。自定义异常类继承了 PHP 异常类的所有属性和方法。还可以将自定义方法添加到自定义异常类中。让我们看看下面的例子:

#### 例子

[Download](../examples/bin/download-source.php?topic=php&file=using-custom-exceptions "Download Source Code")

```
<?php
// Extending the Exception class
class EmptyEmailException extends Exception {}
class InvalidEmailException extends Exception {}

$email = "someuser@example..com";

try{
    // Throw exception if email is empty
    if($email == ""){
        throw new EmptyEmailException("<p>Please enter your E-mail address!</p>");
    }

    // Throw exception if email is not valid
    if(filter_var($email, FILTER_VALIDATE_EMAIL) === FALSE) {           
        throw new InvalidEmailException("<p><b>$email</b> is not a valid E-mail address!</p>");
    }

    // Display success message if email is valid
    echo "<p>SUCCESS: Email validation successful.</p>";
} catch(EmptyEmailException $e){
    echo $e->getMessage();
} catch(InvalidEmailException $e){
    echo $e->getMessage();
}
?>
```

在上面的例子中，我们已经从异常基类中派生了两个新的异常类: **EmptyEmailException** 和 **InvalidEmailException** 。多个`catch`块用于显示不同的错误信息，这取决于生成的异常类型。

由于这些自定义异常类继承了异常类的属性和方法，所以我们可以使用异常的类方法，如`getMessage()`、`getLine()`、`getFile()`等。从异常对象中检索错误信息。

* * *

## 设置全局异常处理程序

正如我们在本章前面所讨论的，如果一个异常没有被捕获，PHP 会产生一个致命的错误“未捕获的异常…”消息。此错误消息可能包含敏感信息，如文件名和出现问题的行号。如果不想向用户公开这样的信息，可以创建一个自定义函数并用`set_exception_handler()`函数注册它来处理所有未捕获的异常。

#### 例子

[Download](../examples/bin/download-source.php?topic=php&file=set-a-default-exception-handler "Download Source Code")

```
<?php
function handleUncaughtException($e){
    // Display generic error message to the user
    echo "Opps! Something went wrong. Please try again, or contact us if the problem persists.";

    // Construct the error string
    $error = "Uncaught Exception: " . $message = date("Y-m-d H:i:s - ");
    $error .= $e->getMessage() . " in file " . $e->getFile() . " on line " . $e->getLine() . "\n";

    // Log details of error in a file
    error_log($error, 3, "var/log/exceptionLog.log");
}

// Register custom exception handler
set_exception_handler("handleUncaughtException");

// Throw an exception
throw new Exception("Testing Exception!");
?>
```

 ***注意:**一个未被捕获的异常总是会导致脚本终止。因此，如果您希望脚本在异常发生点之后继续执行，您必须为每个`try`块至少准备一个相应的`catch`块。**